# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: R
bioc_required: true
sudo: required
before_install:
  tlmgr install knitr
